### PR TITLE
Custom class names

### PR DESCRIPTION
**Pull request by andrew-tam-000**
As discussed, this addresses this issue:

https://github.com/patrik-piskay/react-tabs-redux/issues/14

### CODE REVIEW

**Comment by patrik-piskay** [comment]
Looks good 👍 would you be up for updating the documentation too?

**Comment by andrew-tam-000** [comment]
Yup sure thing, I'll update.  Looks like just the main README.md?

**Comment by andrew-tam-000** [comment]
Sure thing, just updated my PR.

**Comment by patrik-piskay** [comment]
Perfect, thanks!

**Pull request merged**
